travis:
  secure:
    BINSTAR_TOKEN: TNuRqb2pH4OCjcpmDbRRbSxsH5m7cu0jMSfjJ7rjf68Hdcsr4s7yhH3qP3dAE/ckIVuku8fnbXGJ6DJ3zmUBBNtcYnFGDJZox2s38u0jO3iFtus+wgSaqfwzrzST8ZYo11T04PPg1rsQ1RINA/0skXyFZr0cG2qGAYU2Zj6xrZfV6gZJtMQPAG0nXOiUiGHHAzR1wqoHbS314JGQPaojloJX/CyIeJcm/lMOJkBlRqS/rwU4844CmFLXJpYbhIFr225zdbhHeVcvM3P6VSBl9p+bS4Tpbob82FPYlbWEh2LzC2l1vu0CPHsbCRpkgcRbhS808/17hbU1oVR/TsNFEjbBWjiEPZy/PJNwOkyWC8upYBHrQhXLlru7zoQS606HjsWcLtri/kbJ+4ZzyUtUwS9WmehOJOkJD7H4OpXJe9jfSa5eHq0WZNjKar3NGFpdTRRCuqj13cceR4QWjwZ9tBZOy0r5xGFzhMXqB+H8toJtvHhJt3grK37S9Sl/vxqPqhLTN8JMg4QAa2o84VlbeZp0WrpitAQqneNcvju06EetHDz+hXGwEQ/JnVhVShS9FaDPUiVITXAzKe3Xb+sUqu5oieK13EBH7qkYRHPHW4cm9BHXqa+qsSQ5QPQJedWiM8LZCqD/Njh6fXypa11yonaLru1DJCR2g65eirgIxlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
